library super_stop_watch;
// -----------------------------------------------------------------------------
import 'package:basics/super_box/super_box.dart';
import 'package:flutter/material.dart';
import 'package:stop_watch_timer/stop_watch_timer.dart';
// -----------------------------------------------------------------------------
part 'stop_watch/stop_watch_button.dart';
part 'stop_watch/stop_watch_controller.dart';
part 'stop_watch/stop_watch_counter_builder.dart';
part 'stop_watch/stop_watch_records_builder.dart';
// -----------------------------------------------------------------------------
