name: basics
description: You can't build a flutter app without the basics
version: 5.3.9
publish_to: "none"
homepage: https://github.com/RagehAz/basics.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
# --------------------------------------------------------------------------------
  clipboard: ^0.1.3
  collection: ^1.17.2
  image: ^4.0.17
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  device_info_plus: ^9.0.3
  connectivity_plus: ^4.0.2
  permission_handler: ^11.0.0
  wechat_camera_picker: ^4.0.2
  another_flushbar: ^1.12.30
  websafe_svg: ^3.0.0+5
  image_editor: ^1.3.0
  matrix2d: ^1.0.4
  flutter_spinkit: ^5.2.0
  page_transition: ^2.1.0
  sembast: ^3.5.0+1
  sembast_web: ^2.1.3
  package_info_plus: ^4.1.0
  stop_watch_timer: ^3.0.1
  just_audio: ^0.9.35
  crop_your_image: ^0.7.5
  video_player: ^2.7.1
  youtube_player_flutter: ^8.1.2
  wechat_assets_picker: ^8.4.3
  image_picker: ^1.0.4
  image_compression_flutter: ^1.0.3
  android_path_provider: ^0.3.0
  flutter_udid: ^2.0.1
  sentry_flutter: ^7.9.0
  # USED IN FIRE
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  http: ^0.13.0
  intl: ^0.18.0
dependency_overrides:
  intl: ^0.18.1
  # --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_background: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_foreground: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - lib/bldrs_theme/assets/
    - lib/bldrs_theme/assets/aw/
    - lib/bldrs_theme/assets/icons/
    - lib/bldrs_theme/assets/languages/
    - lib/bldrs_theme/assets/planet/
    - lib/bldrs_theme/assets/planet/flags/
    - lib/bldrs_theme/assets/planet/cities/
    - lib/bldrs_theme/assets/sounds/
# --------------------------------------------------------------------------------
  fonts:
    - family: BldrsLogoFont
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bebas.ttf

    - family: BldrsHeadlineFont
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/english/Roboto_Thin.ttf
        - asset: lib/bldrs_theme/assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/Tajawal_Light.ttf
        - asset: lib/bldrs_theme/assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf
# --------------------------------------------------------------------------------
