name: basics
description: You can't build a flutter app without the basics
version: 2.0.1
publish_to: "none"
homepage: https://github.com/RagehAz/typers.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=2.19.6 <3.0.0' # nour's recommendation ">=3.0.0 < 4.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # ------------------------------------
  clipboard: ^0.1.3
  collection: ^1.17.0
  image: ^4.0.17
  path: ^1.8.2
  path_provider: ^2.0.15
  http: ^0.13.6
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.8.1
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  permission_handler: ^10.3.0
  wechat_camera_picker: ^3.8.0
  another_flushbar: ^1.12.30
  websafe_svg: ^3.0.0+5
  image_editor: ^1.3.0
  matrix2d: ^1.0.4
  flutter_spinkit: ^5.2.0
  page_transition: ^2.0.9
  sembast: ^3.4.9
  sembast_web: ^2.1.3
  package_info_plus: ^4.0.2
  intl: ^0.18.0
  # ------------------------------------
#  bldrs_theme:
#    git:
#      url: https://github.com/RagehAz/bldrs_theme.git
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_background: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_foreground: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - lib/bldrs_theme/assets/
    - lib/bldrs_theme/assets/aw/
    - lib/bldrs_theme/assets/icons/
    - lib/bldrs_theme/assets/icons/flags/
    - lib/bldrs_theme/assets/languages/
    - lib/bldrs_theme/assets/planet/
    - lib/bldrs_theme/assets/sounds/
# --------------------------------------------------------------------------------
  fonts:
    - family: BldrsHeadlineFont
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/english/Roboto_Thin.ttf
        - asset: lib/bldrs_theme/assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/arabic/Tajawal_Light.ttf
        - asset: lib/bldrs_theme/assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: lib/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf
# --------------------------------------------------------------------------------
