name: basics
description: You can't build a flutter app without the basics.
version: 4.9.1
publish_to: "none"
homepage: https://github.com/RagehAz/basics.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
# --------------------------------------------------------------------------------
  clipboard: ^0.1.3
  collection: ^1.18.0
  image: ^4.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  dismissible_page: ^1.0.2
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  another_flushbar: ^1.12.30
  image_editor: ^1.5.1
  matrix2d: ^1.0.4
  flutter_spinkit: ^5.2.1
  page_transition: ^2.1.0
  sembast: ^3.7.1+2
  sembast_web: ^2.4.0+2
  package_info_plus: ^8.0.0
  stop_watch_timer: ^3.1.1
  just_audio: ^0.9.38
  crop_your_image: ^1.1.0
  video_player: ^2.8.6
  youtube_player_flutter: 9.0.1
  wechat_camera_picker: ^4.2.2
  wechat_assets_picker: ^9.0.4
  image_picker: ^1.1.2
  image_compression_flutter: ^1.0.4
  android_path_provider: ^0.3.0
  flutter_udid: ^3.0.0
  sentry_flutter: ^8.2.0
  ffmpeg_kit_flutter: ^6.0.3
  video_editor: ^3.0.0
  cross_file_image: ^1.1.0
  cross_file: ^0.3.4+1
  email_validator: ^2.1.17

  cloud_firestore: ^4.17.5
  http: ^1.2.1
  intl: ^0.19.0
  mime: ^1.0.5
  flutter_svg: ^2.0.10+1
  websafe_svg: ^3.0.1+1

  flutter_cache_manager: ^3.3.2
  device_info_plus: ^9.1.2
  # --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_background: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_foreground: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - lib/bldrs_theme/assets/
    - lib/bldrs_theme/assets/aw/
    - lib/bldrs_theme/assets/icons/
    - lib/bldrs_theme/assets/languages/
    - lib/bldrs_theme/assets/planet/
    - lib/bldrs_theme/assets/planet/flags/
    - lib/bldrs_theme/assets/planet/cities/
    - lib/bldrs_theme/assets/sounds/
# --------------------------------------------------------------------------------
  fonts:
    - family: head
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/head.ttf

    - family: body
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/body.ttf

# --------------------------------------------------------------------------------
