name: basics
description: You can't build a flutter app without the basics
version: 1.0.8
publish_to: "none"
homepage: https://github.com/RagehAz/typers.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=2.19.6 <3.0.0' # nour's recommendation ">=3.0.0 < 4.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # ------------------------------------
  clipboard: ^0.1.3
  collection: ^1.17.0
  image: ^4.0.17
  path: ^1.8.2
  path_provider: ^2.0.15
  http: ^0.13.6
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.8.1
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  permission_handler: ^10.3.0
  wechat_camera_picker: ^3.8.0
  another_flushbar: ^1.12.30
  websafe_svg: ^3.0.0+5
  image_editor: ^1.3.0
  matrix2d: ^1.0.4
  flutter_spinkit: ^5.2.0
  page_transition: ^2.0.9
  sembast: ^3.4.9
  sembast_web: ^2.1.3
  package_info_plus: ^4.0.2
  intl: ^0.18.0
  # ------------------------------------
#  bldrs_theme:
#    git:
#      url: https://github.com/RagehAz/bldrs_theme.git
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter:
