name: basics
description: You can't build a flutter app without the basics.
version: 7.2.2
publish_to: "none"
homepage: https://github.com/RagehAz/basics.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # -----------------
  # DISCONTINUED
#  flutter_ffmpeg: ^0.4.2
  video_thumbnail: ^0.5.6
  flutter_native_video_trimmer: ^1.1.9
#  flutter_video_info: 1.3.1
#  ffmpeg_kit_min_gpl_unify: ^6.0.3-LTS
  # ------------------------------------
  ffmpeg_kit_flutter:
    # ----------------
    # IOS
#     path: /Users/rageh/projects/bldrs/that_kit/flutter/flutter
    # ----------------
    # ANDROID
#     path: D:/projects/other/that_kit/flutter/flutter
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/that_kit.git
      path: flutter/flutter
      ref: main
  # -----------------
#  ffmpeg_kit_min_gpl: ^6.0.3+1
  # -----------------
  # COMPLEX DEPENDANTS
  clipboard: ^3.0.14
  collection: ^1.19.1
  mime: 2.0.0
  path: ^1.9.1
  intl: ^0.20.2
  # ----------------
  flutter_image_compress: ^2.5.1
  gallery_saver_plus: ^3.2.9
  file_picker: ^11.0.2
  # ----------------
  # uses or overrides a deprecated API : SUPPRESSED BY [options.compilerArgs << "-Xlint:none"] in android gradle
  video_editor: 3.0.0
  # ----------------
  # JAVA PROBLEMATIC
  path_provider: ^2.1.6
  connectivity_plus: ^7.3.1
  just_audio: ^0.10.6
  video_player: ^2.13.0
  wechat_camera_picker: ^4.6.0
  wechat_assets_picker: ^10.1.3
  image_picker: ^1.2.3
  flutter_cache_manager: ^3.4.2
  # ----------------
  # MAKE NOISE (Deprecated in Java) : SUPPRESSED BY [kotlin.incremental=false] in gradle.properties
  package_info_plus: ^9.0.1
  sentry_flutter: ^9.25.0
  image_editor: 1.6.0
  flutter_udid: ^4.1.6
  # related to pdfx
  device_info_plus: ^12.4.0
  # ----------------
  # COOL
  image: ^4.9.1
  dismissible_page: 1.0.2
  permission_handler: ^12.0.3
  another_flushbar: ^2.2.4
  matrix2d: 1.0.4
  flutter_spinkit: ^5.2.2
  page_transition: ^2.2.2
  sembast: ^3.8.9+1
  sembast_web: ^2.4.5+1
  stop_watch_timer: 3.2.2
  cross_file_image: 1.1.0
  cross_file: ^0.3.5+4
  flutter_svg: ^2.3.0
  websafe_svg: 3.0.1+10
  cloud_firestore: ^6.7.1
  pinch_zoom_release_unzoom: 2.0.0
  http: ^1.6.0
  # related to firebase_ui_auth
  email_validator: ^3.0.0
  # -----------------
#  youtube_player_flutter: ^9.0.4
#  android_path_provider: ^0.3.0
  objectbox: ^5.3.2
  objectbox_flutter_libs: any
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  build_runner: ^2.15.1
  objectbox_generator: ^5.3.2
# --------------------------------------------------------------------------------
objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: ldbob/src/generated
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other
# --------------------------------------------------------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_background: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_foreground: "lib/bldrs_theme/assets/aw/aw_bldrs_app_icon.png"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - lib/bldrs_theme/assets/
    - lib/bldrs_theme/assets/aw/
    - lib/bldrs_theme/assets/icons/
    - lib/bldrs_theme/assets/languages/
    - lib/bldrs_theme/assets/planet/
    - lib/bldrs_theme/assets/planet/flags/
    - lib/bldrs_theme/assets/planet/cities/
    - lib/bldrs_theme/assets/sounds/
# --------------------------------------------------------------------------------
  fonts:
    - family: head
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/head.ttf

    - family: body
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/body.ttf

    - family: bebas
      fonts:
        - asset: lib/bldrs_theme/assets/fonts/bebas.ttf
# --------------------------------------------------------------------------------
