library super_text_field;
// -----------------------------------------------------------------------------
import 'package:basics/helpers/classes/checks/tracers.dart';
import 'package:basics/helpers/classes/space/borderers.dart';
import 'package:basics/helpers/classes/strings/text_directioners.dart';
import 'package:basics/helpers/classes/strings/text_mod.dart';
import 'package:basics/super_text/super_text.dart';
import 'package:flutter/material.dart';
import 'src/text_field/b_super_text_field_box.dart';
import 'src/text_field/c_text_field_form_switcher.dart';
// -----------------------------------------------------------------------------
part 'src/text_field/a_super_text_field.dart';
part 'src/text_field/x_super_text_field_controller.dart';
part 'src/validation/super_validator.dart';
// -----------------------------------------------------------------------------
