library night_sky;
// -----------------------------------------------------------------------------
import 'package:basics/bldrs_theme/classes/colorz.dart';
import 'package:basics/helpers/classes/space/scale.dart';
import 'package:flutter/material.dart';
import 'src/sky_structure/sky_stars.dart';
// -----------------------------------------------------------------------------
part 'src/night_sky.dart';
part 'src/sky_type.dart';
// -----------------------------------------------------------------------------
